name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Run npm
        run: npm ci

      - name: Process data
        run: |
          node data/load-data.js
          mv indiNav.json sdgs.json indicators.json ./data/
          npm run generate:gh-pages  
          
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: dist
